#pragma once

#include <string_view>

namespace senaistream::ui {

  inline constexpr std::string_view management_page = R"HTML(<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light">
<title>SenaiStream</title>
<style>
:root{font-family:"Segoe UI Variable","Segoe UI",sans-serif;color:#171827;background:#eef2fb;--blue:#4857f5;--violet:#7957e9;--green:#17a875;--muted:#777b91;--line:rgba(65,72,120,.11);--glass:rgba(255,255,255,.72);--shadow:0 18px 50px rgba(56,63,112,.12)}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:linear-gradient(135deg,#f5f6fb 0%,#e8f1ff 52%,#f7f1ff 100%)}
body:before,body:after{content:"";position:fixed;border-radius:50%;filter:blur(3px);pointer-events:none}body:before{width:520px;height:520px;left:-210px;top:-260px;background:radial-gradient(circle,rgba(159,185,255,.55),transparent 68%)}body:after{width:520px;height:520px;right:-180px;bottom:-290px;background:radial-gradient(circle,rgba(207,172,255,.48),transparent 68%)}
button,input,select{font:inherit}.app{position:relative;height:100%;z-index:1}.content{height:100%;overflow:auto;padding:30px max(32px,calc((100vw - 1080px)/2)) 118px;scrollbar-width:none}.content::-webkit-scrollbar{display:none}
.glass{background:linear-gradient(145deg,rgba(255,255,255,.86),rgba(255,255,255,.56));border:1px solid rgba(255,255,255,.88);box-shadow:var(--shadow);backdrop-filter:blur(26px) saturate(145%);-webkit-backdrop-filter:blur(26px) saturate(145%)}
.top{display:flex;align-items:center;justify-content:space-between;margin:0 2px 25px}.brand{display:flex;align-items:center;gap:12px}.logo{width:40px;height:40px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#7962ee,#55c8f5);color:#fff;font-weight:800;box-shadow:0 10px 24px rgba(82,91,224,.23)}.brand b{font-size:18px}.brand span{display:block;color:#8c90a2;font-size:11px;margin-top:2px}.online{display:flex;align-items:center;gap:9px;padding:9px 14px;border:1px solid rgba(23,168,117,.13);border-radius:99px;background:rgba(255,255,255,.58);color:#267d61;font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:#25c58c;box-shadow:0 0 0 5px rgba(37,197,140,.12)}
.page{display:none;animation:enter .2s ease}.page.active{display:block}@keyframes enter{from{opacity:.2;transform:translateY(4px)}to{opacity:1;transform:none}}
.hero{border-radius:30px;padding:34px 38px;min-height:205px;display:flex;align-items:center;justify-content:space-between;overflow:hidden;position:relative}.hero:after{content:"";position:absolute;width:330px;height:330px;right:-80px;top:-150px;border-radius:50%;background:radial-gradient(circle,rgba(93,115,245,.18),transparent 68%)}.hero-copy{position:relative;z-index:1}.hero small{color:#6d7390;letter-spacing:1.4px;text-transform:uppercase}.hero h1{margin:12px 0 8px;font-size:38px;line-height:1.08;letter-spacing:-1.5px}.hero p{margin:0;color:#75798e;font-size:14px}.play{position:relative;z-index:1;width:124px;height:124px;border-radius:38px;background:linear-gradient(145deg,#785eea,#54c8ef);box-shadow:0 22px 44px rgba(79,87,215,.25);display:grid;place-items:center;color:#fff;font-size:34px;transform:rotate(6deg)}.play span{transform:rotate(-6deg);margin-left:5px}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:14px}.stat{border-radius:22px;padding:21px 22px}.stat label{display:block;color:#85899d;font-size:11px;text-transform:uppercase;letter-spacing:.5px}.stat strong{display:block;margin-top:10px;font-size:21px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.good{color:var(--green)}
.quick{margin-top:14px;border-radius:22px;padding:21px 24px;display:flex;align-items:center;justify-content:space-between;gap:20px}.quick b{font-size:14px}.quick span{display:block;color:#85899c;font-size:12px;margin-top:4px}.ip{background:#f0f2ff;border:1px solid rgba(72,87,245,.09);padding:10px 15px;border-radius:12px;color:#4250da;font-weight:700}
.heading{display:flex;align-items:end;justify-content:space-between;margin:4px 2px 18px}.heading h1{margin:0;font-size:28px;letter-spacing:-.8px}.heading p{margin:5px 0 0;color:var(--muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{border-radius:22px;padding:22px}.wide{grid-column:1/-1}.card label,.pin label{display:block;font-size:12px;font-weight:650;margin-bottom:9px}.hint{color:#9295a6;font-size:10px;margin-top:8px}.control,select,input[type=number],input[type=text]{width:100%;padding:11px 12px;border-radius:12px;border:1px solid var(--line);background:rgba(246,247,253,.75);color:#242538;outline:none}.control:focus,select:focus,input:focus{border-color:rgba(72,87,245,.35);box-shadow:0 0 0 3px rgba(72,87,245,.07)}select option{background:#fff}.range{display:flex;align-items:center;gap:18px}.range input{width:100%;accent-color:var(--blue)}.rate{min-width:92px;padding:9px 11px;text-align:center;border-radius:12px;background:#eef0ff;color:#4552de;font-size:12px}.switch-row{display:flex;align-items:center;justify-content:space-between}.switch{appearance:none;width:44px;height:24px;border:0;border-radius:99px;background:#d7d9e3;position:relative;cursor:pointer}.switch:after{content:"";position:absolute;width:18px;height:18px;border-radius:50%;background:#fff;left:3px;top:3px;box-shadow:0 2px 5px #8893;transition:.18s}.switch:checked{background:linear-gradient(90deg,var(--violet),#55bde9)}.switch:checked:after{left:23px}.actions{display:flex;align-items:center;justify-content:flex-end;gap:13px;margin-top:16px}.primary{border:0;border-radius:13px;background:linear-gradient(100deg,#6657e8,#526af4);color:#fff;font-weight:700;padding:11px 20px;cursor:pointer;box-shadow:0 10px 25px rgba(78,88,215,.2)}.primary:hover{filter:brightness(1.04);transform:translateY(-1px)}
.screen-card{border-radius:28px;padding:30px;display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center}.screen-art{min-height:300px;display:grid;place-items:center}.monitor{width:min(390px,90%);aspect-ratio:16/10;border:5px solid rgba(255,255,255,.9);border-radius:22px;background:linear-gradient(145deg,#dce7ff,#e9dcff);box-shadow:0 26px 55px rgba(73,83,157,.2),inset 0 0 45px rgba(255,255,255,.55);display:grid;place-items:center;color:#5965dc;font-size:42px;font-weight:800}.screen-copy h1{font-size:31px;margin:0 0 8px;letter-spacing:-1px}.screen-copy p{margin:0;color:var(--muted);font-size:13px}.segmented{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:6px;border-radius:16px;background:#eff1f8;margin-top:25px}.segmented button{border:0;border-radius:11px;background:transparent;padding:12px;color:#73768a;font-weight:650;cursor:pointer}.segmented button.active{background:#fff;color:#4857e6;box-shadow:0 6px 18px rgba(64,71,116,.12)}.screen-state{margin-top:14px;color:#777b8f;font-size:12px}.screen-state b{color:#25273b}
.pair{display:none;border-radius:22px;padding:24px;margin-bottom:14px}.pair.visible{display:block}.pin-row{display:flex;align-items:end;gap:12px}.pin{flex:1}.pin input{max-width:250px;font-size:23px;letter-spacing:9px;text-align:center}.empty{min-height:270px;border-radius:25px;display:grid;place-items:center;text-align:center;padding:30px}.empty-icon{width:66px;height:66px;margin:0 auto 14px;border-radius:22px;display:grid;place-items:center;background:#eef0ff;color:#5966e7;font-size:26px}.empty h2{font-size:18px;margin:0 0 7px}.empty p{font-size:12px;color:var(--muted);margin:0}.device-count{margin-top:13px;color:#4855d8;font-weight:650;font-size:12px}.system-list{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.system-item{border-radius:20px;padding:20px}.system-item span{display:block;color:#8a8da0;font-size:11px}.system-item b{display:block;margin-top:8px;font-size:14px}
.dock-wrap{position:fixed;z-index:8;left:0;right:0;bottom:18px;display:flex;justify-content:center;pointer-events:none}.dock{pointer-events:auto;display:flex;align-items:center;gap:7px;padding:8px;border-radius:22px;background:rgba(255,255,255,.78);border:1px solid rgba(255,255,255,.92);box-shadow:0 18px 50px rgba(49,56,104,.18);backdrop-filter:blur(28px) saturate(160%)}.dock button{border:0;background:transparent;border-radius:15px;padding:9px 16px;color:#838698;cursor:pointer;min-width:94px}.dock i{display:block;font-style:normal;font-size:17px;margin-bottom:3px}.dock span{font-size:10px}.dock button.active{background:linear-gradient(135deg,#6658e9,#4d72f3);color:#fff;box-shadow:0 8px 20px rgba(69,83,216,.24)}
.toast{position:fixed;right:24px;top:22px;z-index:12;background:rgba(255,255,255,.92);border:1px solid #fff;border-radius:14px;padding:12px 16px;box-shadow:var(--shadow);font-size:12px;opacity:0;transform:translateY(-60px);transition:.22s}.toast.show{opacity:1;transform:none}.toast.error{color:#c63e56}.saving{opacity:.6;pointer-events:none}
@media(max-width:760px){.content{padding:18px 14px 108px}.hero{padding:28px 24px}.hero h1{font-size:30px}.play{display:none}.stats,.grid,.system-list{grid-template-columns:1fr}.wide{grid-column:auto}.screen-card{grid-template-columns:1fr;padding:22px}.screen-art{min-height:210px}.dock button{min-width:58px;padding:9px 10px}.dock span{display:none}.pin-row{align-items:stretch;flex-direction:column}}
</style>
</head>
<body>
<div class="app"><main class="content">
  <header class="top"><div class="brand"><div class="logo">S</div><div><b>SenaiStream</b><span>Moonlight host</span></div></div><div class="online"><span class="dot"></span><span id="topStatus">Pronto</span></div></header>

  <section class="page active" id="overview">
    <article class="hero glass"><div class="hero-copy"><small>Baixa latência</small><h1>Pronto para transmitir.</h1><p>Abra o Moonlight e escolha Desktop.</p></div><div class="play"><span>▶</span></div></article>
    <div class="stats"><article class="stat glass"><label>Transmissão</label><strong class="good" id="streamState">Aguardando</strong></article><article class="stat glass"><label>Pareados</label><strong id="pairedCount">0 dispositivos</strong></article><article class="stat glass"><label>Tela</label><strong id="screenMode">Estendida</strong></article></div>
    <article class="quick glass"><div><b>Endereço do host</b><span>Adicione este IP no Moonlight</span></div><div class="ip" id="hostAddress">Carregando…</div></article>
  </section>

  <section class="page" id="stream">
    <div class="heading"><div><h1>Transmissão</h1><p>Imagem e desempenho.</p></div><span id="message"></span></div>
    <form id="form"><input id="width" name="width" type="hidden"><input id="height" name="height" type="hidden"><input name="codec" type="hidden" value="h264"><input id="virtualDisplay" name="virtualDisplay" type="hidden" value="1">
      <div class="grid"><article class="card glass"><label for="displayInput">Monitor</label><select class="control" id="displayInput" name="display"><option value="0">Detectando…</option></select></article><article class="card glass"><label for="resolution">Resolução</label><select class="control" id="resolution"><option value="0x0">Automática</option><option value="1280x720">1280 × 720</option><option value="1920x1080">1920 × 1080</option><option value="2560x1440">2560 × 1440</option><option value="3840x2160">3840 × 2160</option></select></article><article class="card glass"><label for="fps">FPS</label><select class="control" id="fps" name="fps"><option value="0">Automático</option><option value="30">30 FPS</option><option value="60">60 FPS</option><option value="90">90 FPS</option><option value="120">120 FPS</option></select></article><article class="card glass"><div class="switch-row"><div><label for="hardware">Encoder da GPU</label><div class="hint">Menor atraso</div></div><input class="switch" id="hardware" name="hardware" type="checkbox" value="1"></div></article><article class="card glass wide"><label for="bitrate">Taxa de bits</label><div class="range"><input id="bitrate" name="bitrateMbps" type="range" min="5" max="100" step="5"><span class="rate"><b id="bitrateValue">20</b> Mbps</span></div></article></div>
      <div class="actions"><button class="primary" type="submit">Aplicar agora</button></div>
    </form>
  </section>

  <section class="page" id="display">
    <article class="screen-card glass"><div class="screen-art"><div class="monitor">S</div></div><div class="screen-copy"><h1>Tela virtual</h1><p>Troque o modo sem sair do Moonlight.</p><div class="segmented"><button id="extendButton" type="button" data-mode="extend">Estender</button><button id="duplicateButton" type="button" data-mode="duplicate">Duplicar</button></div><div class="screen-state">Modo atual: <b id="displayState">detectando…</b></div></div></article>
  </section>

  <section class="page" id="devices">
    <div class="heading"><div><h1>Dispositivos</h1><p>Clientes Moonlight autorizados.</p></div></div>
    <article class="pair glass" id="pairCard"><h2>Novo pareamento</h2><div class="pin-row"><div class="pin"><label for="pin">PIN do Moonlight</label><input class="control" id="pin" inputmode="numeric" maxlength="4" autocomplete="one-time-code" placeholder="••••"></div><button class="primary" id="pinButton" type="button">Confirmar</button></div></article>
    <article class="empty glass" id="deviceEmpty"><div><div class="empty-icon">◇</div><h2>Nenhum pedido pendente</h2><p>Inicie o pareamento pelo Moonlight.</p><div class="device-count" id="deviceCount">0 dispositivos pareados</div></div></article>
  </section>

  <section class="page" id="system">
    <div class="heading"><div><h1>Sistema</h1><p>Host instalado.</p></div></div><div class="system-list"><article class="system-item glass"><span>Versão</span><b>0.4.0</b></article><article class="system-item glass"><span>Vídeo</span><b>H.264 · baixa latência</b></article><article class="system-item glass"><span>Captura</span><b>DXGI</b></article><article class="system-item glass"><span>Áudio</span><b>WASAPI · Opus</b></article></div>
  </section>
</main></div>

<div class="dock-wrap"><nav class="dock" aria-label="Navegação"><button class="active" data-page="overview"><i>⌂</i><span>Início</span></button><button data-page="stream"><i>◉</i><span>Transmissão</span></button><button data-page="display"><i>▣</i><span>Tela</span></button><button data-page="devices"><i>◇</i><span>Dispositivos</span></button><button data-page="system"><i>···</i><span>Sistema</span></button></nav></div>
<div class="toast" id="toast"></div>
<script>
const $=selector=>document.querySelector(selector),form=$('#form'),resolution=$('#resolution'),bitrate=$('#bitrate'),toast=$('#toast');let currentMode='extend';
document.querySelectorAll('.dock button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.dock button').forEach(item=>item.classList.remove('active'));document.querySelectorAll('.page').forEach(item=>item.classList.remove('active'));button.classList.add('active');$('#'+button.dataset.page).classList.add('active')});
function notify(text,ok=true){toast.textContent=text;toast.className='toast show '+(ok?'':'error');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.className='toast',2800)}
function setModeVisual(mode){currentMode=mode;$('#virtualDisplay').value=mode==='extend'?'1':'0';$('#extendButton').classList.toggle('active',mode==='extend');$('#duplicateButton').classList.toggle('active',mode==='duplicate');$('#displayState').textContent=mode==='extend'?'Estendida':'Duplicada';$('#screenMode').textContent=mode==='extend'?'Estendida':'Duplicada'}
async function loadDisplays(selected){const catalog=await fetch('/api/displays').then(response=>response.json());form.display.innerHTML='';let preferred='';for(const display of catalog.displays){const option=document.createElement('option');option.value=display.index;option.textContent=(display.virtual?'Virtual · ':(display.primary?'Principal · ':''))+display.name+' · '+display.width+'×'+display.height;form.display.appendChild(option);if((currentMode==='extend'&&display.virtual)||(currentMode==='duplicate'&&display.primary))preferred=String(display.index)}if(!catalog.displays.length){const option=document.createElement('option');option.value='0';option.textContent='Nenhuma tela ativa';form.display.appendChild(option)}form.display.value=selected!==undefined?String(selected):preferred}
Promise.all([fetch('/api/settings').then(response=>response.json()),loadDisplays()]).then(([settings])=>{form.display.value=String(settings.display);form.width.value=settings.width;form.height.value=settings.height;form.fps.value=String(settings.fps);if(![...form.fps.options].some(option=>option.value===String(settings.fps))){const option=document.createElement('option');option.value=settings.fps;option.textContent=settings.fps+' FPS';form.fps.appendChild(option);form.fps.value=String(settings.fps)}bitrate.value=settings.bitrateMbps;form.hardware.checked=settings.hardware;const size=settings.width+'x'+settings.height;resolution.value=[...resolution.options].some(option=>option.value===size)?size:'0x0';$('#bitrateValue').textContent=bitrate.value;setModeVisual(settings.virtualDisplay?'extend':'duplicate')}).catch(()=>notify('Host indisponível.',false));
bitrate.oninput=()=>$('#bitrateValue').textContent=bitrate.value;
resolution.onchange=()=>{const parts=resolution.value.split('x');form.width.value=parts[0];form.height.value=parts[1]};
form.onsubmit=async event=>{event.preventDefault();const payload=new URLSearchParams(new FormData(form));if(!form.hardware.checked)payload.set('hardware','0');const response=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:payload});const text=await response.text();$('#message').textContent=response.ok?'Aplicado':text;notify(response.ok?'Aplicado na transmissão.':text,response.ok)};
async function changeDisplayMode(mode){const buttons=[$('#extendButton'),$('#duplicateButton')];buttons.forEach(button=>button.classList.add('saving'));try{const response=await fetch('/api/display-mode',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({mode})});const text=await response.text();if(response.ok){setModeVisual(mode);await loadDisplays();notify(text)}else notify(text,false)}catch{notify('Não foi possível trocar a tela.',false)}finally{buttons.forEach(button=>button.classList.remove('saving'))}}
$('#extendButton').onclick=()=>changeDisplayMode('extend');$('#duplicateButton').onclick=()=>changeDisplayMode('duplicate');
async function refresh(){try{const status=await fetch('/api/status').then(response=>response.json());$('#streamState').textContent=status.active?'Transmitindo':'Aguardando';$('#topStatus').textContent=status.active?'Transmitindo':'Pronto';$('#pairedCount').textContent=status.pairedClients+(status.pairedClients===1?' dispositivo':' dispositivos');$('#deviceCount').textContent=status.pairedClients+(status.pairedClients===1?' dispositivo pareado':' dispositivos pareados');$('#hostAddress').textContent=status.address;setModeVisual(status.displayMode==='extended'?'extend':'duplicate');$('#pairCard').classList.toggle('visible',status.pairingWaiting);$('#deviceEmpty').style.display=status.pairingWaiting?'none':'grid';if(status.pairingWaiting)document.querySelector('[data-page="devices"]').click()}catch{}}
setInterval(refresh,1000);refresh();
$('#pinButton').onclick=async()=>{const response=await fetch('/api/pin',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({pin:$('#pin').value})});notify(await response.text(),response.ok)};
</script>
</body>
</html>)HTML";  ///< Embedded desktop management experience.

}  // namespace senaistream::ui
